- title: Ballerina OpenAPI support
  url: #
  sublinks:
    - title: Generate Ballerina services from OpenAPI contracts 
      url: /learn/ballerina-openapi-support/#generate-ballerina-services-from-openapi-contracts
      sublinks:
        - title: Generate from tags
          url: /learn/ballerina-openapi-support/#generate-from-tags
          active: generate-from-tags
    - title: Export OpenAPI contracts from Ballerina services 
      url: /learn/ballerina-openapi-support/#export-openapi-contracts-from-ballerina-services 
      sublinks:
        - title: Export in JSON format
          url: /learn/ballerina-openapi-support/#export-in-json-format
          active: export-in-json-format
        - title: Export for a given service
          url: /learn/ballerina-openapi-support/#export-for-a-given-service
          active: export-for-a-specific-service
        - title: Export with a given title and version
          url: /learn/ballerina-openapi-support/#export-with-a-given-title-and-version
          active: export-with-a-given-title-and-version
    - title: OpenAPI validator compiler plugin
      url: /learn/ballerina-openapi-support/#openapi-validator-compiler-plugin
      active: openapi-validator-compiler-plugin
    - title: Generate Ballerina clients from OpenAPI definitions
      url: /learn/ballerina-openapi-support/#generate-ballerina-client-from-openapi-definitions
      sublinks:
        - title: Generate with boiler-plate tests
          url: /learn/ballerina-openapi-support/#generate-with-boiler-plate-tests
          active: generate-with-boiler-plate-tests
        - title: Generate with nillable types
          url: /learn/ballerina-openapi-support/#generate-with-nillable-types
          active: generate-with-nillable-types
    - title: Publish your client
      url: /learn/ballerina-openapi-support/#publish-your-client
      active: publish-your-client
    - title: Annotation reference
      url: /learn/ballerina-openapi-support/#annotation-reference
      active: annotation-reference
