- title: Ballerina OpenAPI support
  url: #
  sublinks:
    - title: Use the capabilities of the OpenAPI tools
      url: /learn/ballerina-openapi-support/#use-the-capabilities-of-the-openapi-tools
      active: use-the-capabilities-of-the-openapi-tools
    - title: Generate a Ballerina service from an OpenAPI definition
      url: /learn/ballerina-openapi-support/#generate-a-ballerina-service-from-an-openapi-definition
      active: generate-a-ballerina-service-from-an-openapi-definition
    - title: Export an OpenAPI contract from a Ballerina service
      url: /learn/ballerina-openapi-support/#export-an-openapi-contract-from-a-ballerina-service
      active: export-an-openapi-contract-from-a-ballerina-service
    - title: OpenAPI validator compiler plugin
      url: /learn/ballerina-openapi-support/#openapi-validator-compiler-plugin
      active: openapi-validator-compiler-plugin
    - title: Generate a Ballerina client from an OpenAPI definition
      url: /learn/ballerina-openapi-support/#generate-a-ballerina-client-from-an-openapi-definition
      active: generate-a-ballerina-client-from-an-openapi-definition
    - title: Contribute to the WSO2 openapi-connectors repository
      url: /learn/ballerina-openapi-support/#contribute-to-the-wso2-openapi-connectors-repository
      active: contribute-to-the-wso2-openapi-connectors-repository
    - title: OpenAPI to Ballerina command reference
      url: /learn/ballerina-openapi-support/#openapi-to-ballerina-command-reference
      active: openapi-to-ballerina-command-reference
    - title: OpenAPI annotation reference
      url: /learn/ballerina-openapi-support/#openapi-annotation-reference
      active: openapi-annotation-reference
