- title: Making Ballerina Programs Configurable 
  url: '#'
  sublinks:
    - title: Defining Configurable Variables 
      url: learn/making-ballerina-programs-configurable/defining-configurable-variables/
      active: defining-configurable-variables
    - title: Providing Values to Configurable Variables
      url: /learn/making-ballerina-programs-configurable/providing-values-to-configurable-variables/
      active: providing-values-to-configurable-variables
    - title: Trying Out Configurability
      url: /learn/making-ballerina-programs-configurable/trying-out-configurability/
      active: trying-out-configurability



