# This is the config of the link checker GitHub Action (i.e., https://github.com/marketplace/actions/link-checker).

on: [pull_request]
name: Link Checker 
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the site
        uses: shafreenAnfar/jekyll-build-action@v5
      - name: Link Checker
        id: lc
        uses: peter-evans/link-checker@v1
        with:
          args: -r learn 1.2 -x 1.0 1.1 https?:// -d ./_site 
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Link Checker Report
          path:  ./link-checker/out.md
      - name: Fail if there were link errors
        run: if [[ $(grep -c ".*" ./link-checker/out.md) == "5" ]]; then echo "Success"; exit 0; else echo "Fail"; exit 1; fi



