# Github action to open a PR in Homebrew/homebrew-core when a new release of ballerina is being published
name: Update Homebrew
# on:
#   release:
#     types: [published]

on:
  push:
    branches:
      - prod-sync
    paths:
    - '_data/latest/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository.
        uses: actions/checkout@v2
      
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
        
      - name: Wget required files
        id: version
        run: wget -O ./.github/scripts/latest_release.json https://product-dist.ballerina.io/downloads/latest_release.json?982
        
      - name: Send the PR to Homebrew
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          version=$(cat ./.github/scripts/latest_release.json | jq '.version')
          version=$(sed -e 's/^"//' -e 's/"$//' <<<"$version")
          
          dist_url="https://product-dist.ballerina.io/downloads/$version/ballerina-$version.zip"
          
          checksum="$(curl -fsSL "$dist_url" | shasum -a 256 -b | awk '{print $1}')"

          if [ -z "$checksum" ]; then
            echo "ERROR: calculating the checksum failed for $dist_url" >&2
            exit 1
          fi

          python3 ./.github/scripts/homebrew_publish.py ${{ secrets.WEBSITE_TOKEN }} "$version" "$checksum" "$dist_url"
      