# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Nextjs app to gh-pages

on:
  workflow_dispatch:
  push:
    branches: [ website-revamp ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      NEXT_PUBLIC_BASE_PATH: ''
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    strategy:
      matrix:
        node-version: [16.x]
        #node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        #cache: 'npm'
    - run: npm ci
    - name: Build project
      run: npm run build
    - name: Export static files
      run: npm run export
    - name: Add .nojekyll file
      run: touch ./out/.nojekyll
    - name: Rearrange files to match the urls  
      run: |
         chmod +x ./utils/rearrangeFiles.sh
         ./utils/rearrangeFiles.sh
      shell: bash
    - name: Deploy
      run: |
        cd ./out
        git init
        git checkout deploy-website-$GITHUB_SHA 2>/dev/null || git checkout -b deploy-website-$GITHUB_SHA
        git config --global user.email "saranimendisb@gmail.com"
        git config --global user.name "sm1990"
        git add .
        git commit --allow-empty -m 'Deploy website'
        git push --set-upstream origin deploy-website-$GITHUB_SHA
        echo 'Successfully pushed to deploy-website-$GITHUB_SHA branch'
    - name: Create pull request for new site
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -b gh-pages -m '[Automated] Deploy website'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}