name: Create PR for new Ballerina by examples pages

on:
  push:
    branches:
      - master
    paths:
      - '_data/stable-latest/**'

jobs:
  bbe-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      env:
        GOPATH: /home/runner/work/ballerina-release
    
    - name: Install Go module blackfriday
      run: go get github.com/russross/blackfriday

    - name: Install jq for json manipulation
      run: sudo apt-get install jq

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone ballerina-release
      run: git clone https://ballerina-bot:$GITHUB_TOKEN@github.com/ballerina-platform/ballerina-release.git

    - name: Generate BBEs
      run: |
        cd ballerina-release

        BALLERINA_VERSION="`jq -r '.version' ../_data/stable-latest/metadata.json`"
        array=($(echo $BALLERINA_VERSION | tr "." "\n"))
        SITE_VERSION="${array[0]}.${array[1]}"

        echo "-----------------------------------------------------------------------------------------------------------------------"
        echo "curl https://dist-dev.ballerina.io/downloads/$BALLERINA_VERSION/ballerina-$BALLERINA_VERSION.zip --output ballerina.zip"
        curl http://dist-dev.ballerina.io/downloads/$BALLERINA_VERSION/ballerina-$BALLERINA_VERSION.zip --output ballerina.zip

        if ! unzip ballerina.zip; then
          exit 1
        fi

        echo "------------------------------------------------------------------------------------------------------------------------------------------------"
        echo "go run ballerinaByExample/tools/generate.go ballerina-$BALLERINA_VERSION/distributions/jballerina-$BALLERINA_VERSION/examples $SITE_VERSION $BBE_GEN_DIR $GEN_FOR_JEKYLL $IS_LATEST_VERSION"
        go run ballerinaByExample/tools/generate.go "ballerina-${BALLERINA_VERSION}/distributions/jballerina-${BALLERINA_VERSION}/examples" $SITE_VERSION "by-example" "true" "true"
        echo "....Completed building BBE Site...."

    - name: Remove old examples file
      run: git rm -r learn/by-example

    - name: Copy newly generated examples file
      run: cp -r ballerina-release/by-example learn/

    - name: Push changes for new BBEs
      run: |
        git checkout automate-bbes-$GITHUB_SHA 2>/dev/null || git checkout -b automate-bbes-$GITHUB_SHA
        git pull origin master
        
        git config --global user.email "ballerina-bot@ballerina.org"
        git config --global user.name "ballerina-bot"
        
        git add learn/by-example
        git commit --allow-empty -m 'Update Ballerina by examples'
        
        git push --set-upstream origin automate-bbes-$GITHUB_SHA
        echo 'Successfully pushed to automate-bbes-$GITHUB_SHA branch'

    - name: Create pull request for new BBEs
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -m '[Automated] Update Ballerina by examples(BBEs) pages for the new release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
