name: Create PR for new Swan Lake BBEs pages on distribution repo changes

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  bbe-sw-gen:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      env:
        GOPATH: /home/runner/work/ballerina-release
    
    - name: Install Go module blackfriday
      run: go get github.com/russross/blackfriday

    - name: Install jq for json manipulation
      run: sudo apt-get install jq

    - name: Checkout code
      uses: actions/checkout@v2
      with:
          ref: master

    - name: Clone ballerina-release
      run: git clone https://ballerina-bot:$GITHUB_TOKEN@github.com/ballerina-platform/ballerina-release.git

    - name: Clone ballerina-distribution
      run: git clone https://ballerina-bot:$GITHUB_TOKEN@github.com/ballerina-platform/ballerina-distribution.git

    - name: Generate BBEs
      run: |
        cd ballerina-release
        cp ../ballerina-distribution/examples/index.json ../_data/all-bbes.json
        cp -r ../ballerina-distribution/examples .

        go run ballerinaByExample/tools/generate.go "examples" "swan-lake" "by-example" "true" "true" "true"

    - name: Remove old examples file
      run: git rm -r learn/by-example

    - name: Copy newly generated examples file
      run: cp -r ballerina-release/by-example learn/

    - name: Push changes for new BBEs
      run: |
        git checkout automate-bbes-$GITHUB_SHA 2>/dev/null || git checkout -b automate-bbes-$GITHUB_SHA
        
        git config --global user.email "ballerina-bot@ballerina.org"
        git config --global user.name "ballerina-bot"
        
        git add _data/all-bbes.json
        git add learn/by-example
        git commit --allow-empty -m 'Update Ballerina Swan Lake by examples'
        
        git push --set-upstream origin automate-bbes-$GITHUB_SHA
        echo 'Successfully pushed to automate-bbes-$GITHUB_SHA branch'

    - name: Create pull request for new BBEs
      shell: bash
      run: |
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub pull-request -b master -m '[Automated] Update Ballerina By Example(BBEs) pages'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
